version: '3.8'

services: 
  
  fluidjs:
    image: node:14.15.5-alpine3.13
    working_dir: /script
    volumes:
      - ./:/script
    command: sh -c "npm install && npm run build"
    deploy:
      restart_policy: 
        condition: none

  test:
    image: nginx:latest
    ports:
      - 3010:80
    volumes:
      - ./:/var/www/html/
      - ./docker/dev/config/webserver/etc/nginx/templates:/etc/nginx/templates:ro
    

    